apache/incubator-spot

- spot-oa/oa/components/nc/network_context.py
Added validation to check if network_context lines are empty or if there are no lines at all.
Also, checks if the line contains at least 2 columns to create a dictionary, if there are 1 or fewer columns then the returned value is ("-","-").
[SPOT-33](https://issues.apache.org/jira/browse/SPOT-33)
> [SPOT-33][OA] Fix for Network context module fails when there is an empty string at the end of the file

- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAWrapper.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/FlowSuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
Changed the place to call InvalidDataHandler.scala for flow suspicious connects analysis. 
This way, the function `showAndSaveCorruptRecords` won't try to filter `scoredFlowRecords` instead it will filter `dataWithWords` in FlowSuspiciousConnectsMode.scala.
Also removing the line from SpotLDAWrapper, documentDictionary.count() since it showed to be taking a long time as well. 
Tested with these changes and time was reduced from 11 hours to 7. 
More about this issue and steps to reproduce in Jira: https://issues.apache.org/jira/browse/SPOT-43
> [Spot-43][ML] Job count at InvalidDataHandler.scala:43 taking too long.

- README.md
The main README.md was pointing to the incorrect slack channel.
> Correct link to slack channel

- README.md
JIRA Issue: https://issues.apache.org/jira/browse/SPOT-132
> SPOT-132: Update spot link to DockerHub

- spot-oa/oa/flow/ipynb_templates/Edge_Investigation_master.ipynb
A typo committed in an previous PR was causing the Edge notebook to crash when it tried to execute a Markup cell as if it were code. 
Closes the bug: https://issues.apache.org/jira/browse/SPOT-139
> Reverting changes in flows Edge notebook

- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxyWordCreation.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/ExponentialCutoffs.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/MathUtils.scala
- spot-ml/src/test/scala/org/apache/spot/QuantilesTest.scala
- spot-ml/src/test/scala/org/apache/spot/proxy/ProxyWordCreationTest.scala
- spot-ml/src/test/scala/org/apache/spot/utilities/ExponentialCutoffsTest.scala
- spot-ml/src/test/scala/org/apache/spot/utilities/MathUtilsTest.scala
- spot-ml/src/test/scala/org/apache/spot/utilities/TimeUtilitiesTest.scala
In this pull request we propose to move away from quantiles and we are also suggesting an additional feature. For more information about the problem statement and advantages of the changes please check the Jira issue: https://issues.apache.org/jira/browse/SPOT-153?jql=project%20%3D%20SPOT
Summary of changes: 
class ProxySuspiciousConnectsModel: We are moving away from quantiles which are computationally expensive and data dependent. In this new version we got rid of the val timeCuts which computed quantiles. We also modified val entropyCuts to have a fixed number of buckets and therefore quantiles are no longer computed. All references to timeCuts and agentCuts were removed.
object ProxyWordCreation: We got rid of the timeCuts and agentCuts references because they are no longer computed …
> SPOT-153 [ML] Feature improvement on proxy and elimination of quantiles

- spot-ml/INSTALL.md
- spot-ml/ML_OPS.md
- spot-ml/README.md
- spot-ml/SPOT-ML-JAR.md
- spot-ml/SUSPICIOUS_CONNECTS_SCHEMA.md
- spot-ml/ml_ops.sh
updated documentation, added separate sections for the data schema, the jar, and the ml_ops.sh script
> doc_restructuring incl. [SPOT-163]

- spot-ml/src/main/scala/org/apache/spot/SuspiciousConnects.scala
- spot-ml/src/main/scala/org/apache/spot/dns/DNSSuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/dns/model/DNSSuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/FlowSuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
- spot-ml/src/test/scala/org/apache/spot/dns/DNSSuspiciousConnectsAnalysisTest.scala
- spot-ml/src/test/scala/org/apache/spot/netflow/FlowSuspiciousConnectsAnalysisTest.scala
- spot-ml/src/test/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModelTest.scala
- spot-ml/src/test/scala/org/apache/spot/proxy/ProxySuspiciousConnectsAnalysisTest.scala
- spot-ml/src/test/scala/org/apache/spot/proxy/ProxyWordCreationTest.scala
This PR implements changes requested on JIRA issue SPOT-128. Includes the elimination of any call to save/write to file system in any place other than the main application.
Also, includes some code cleanup and refactoring.
> Spot-128 Make every pipeline to return results to main program

- spot-ml/ml_ops.sh
Aims to close SPOT-136.
Removed --num-executors from ml_ops.sh and replaced with dynamicAllocation.maxExecutors for the maximum number of executors and stop getting Spark warning about ignoring --num-executors.
> Spot-136 Number of executors is set but also dynamic allocation

- spot-oa/api/graphql/flow/query.py
- spot-oa/ui/dns/js/components/NetworkViewPanel.react.js
- spot-oa/ui/flow/js/components/NetworkViewPanel.react.js
- spot-oa/ui/js/components/PolloNetworkViewMixin.react.js
When ipranges.csv file is present during OA execution, the srcIPInternal and dstIPInternal fields are populated  accordingly. However, the UI is not displaying this information as expected. In the suspicious frame it should include all Internal IP Addresses as blue rectangle. In the Network View the Internal IP Addresses must be represented by blue diamonds
This also impacted the Network view for DNS
> Bug fix - The UI is not displaying the correct layout for internal/external IPs

- spot-ml/src/main/scala/org/apache/spot/SuspiciousConnects.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/data/InputOutputDataHandler.scala
Implements a fix for SPOT-172.
- Added new method to merge part-* files after Spark saves results as text. The new method using FileSystem is going to be used by Proxy which it was having issues with FileUtil.copyMerge.
- Did a quick refactor on scala docs of InputOutputDataHandler.scala, replaced spark with sparkSession.
> Spot-172 Proxy not returning the number of results requested

- spot-ml/src/main/scala/org/apache/spark/sql/WideUDFs.scala
- spot-ml/src/main/scala/org/apache/spot/dns/DNSSuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/dns/model/DNSFeedback.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAWrapper.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAWrapperSchema.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/FlowSuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowFeedback.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxyFeedback.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsAnalysis.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxyWordCreation.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/TopDomains.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/data/InputOutputDataHandler.scala
- spot-ml/src/test/scala/org/apache/spot/SuspiciousConnectsArgumentParserTest.scala
- spot-ml/src/test/scala/org/apache/spot/dns/DNSSuspiciousConnectsAnalysisTest.scala
- spot-ml/src/test/scala/org/apache/spot/dns/DNSSuspiciousConnectsModelTest.scala
- spot-ml/src/test/scala/org/apache/spot/netflow/FlowSuspiciousConnectsAnalysisTest.scala
- spot-ml/src/test/scala/org/apache/spot/proxy/ProxySuspiciousConnectsAnalysisTest.scala
Implements changes requested on SPOT-166
- Fixed Scala docs issues; reference to _spark_ replaced with _sparkSession_
- Added missing Scala docs
- Updated and added unit test; test coverage 84% lines.
> Spot-166 module code cleanup pass

- spot-oa/ui/proxy/js/components/NetworkViewPanel.react.js
Proxys scoring panel was hanging when a date with no data available was selected. At the same time, a unique 'root node' was being displayed in the network view.
This PR adds a couple of validations on the suspicious data to prevent this behavior
> De 127 scoring proxy

- spot-oa/oa/dns/dns_oa.py
Replaced all double spaces in timeframe column with a single space.
Aims to close:
https://issues.apache.org/jira/browse/SPOT-193
> Bug fix - start_oa.py fails for single-digit dates

- spot-ml/src/main/scala/org/apache/spot/dns/model/DNSSuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAHelper.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAModel.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAResult.scala
- spot-ml/src/main/scala/org/apache/spot/lda/SpotLDAWrapper.scala
- spot-ml/src/main/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/proxy/ProxySuspiciousConnectsModel.scala
- spot-ml/src/main/scala/org/apache/spot/utilities/TopDomains.scala
- spot-ml/src/test/scala/org/apache/spot/lda/SpotLDAHelperTest.scala
- spot-ml/src/test/scala/org/apache/spot/lda/SpotLDAWrapperTest.scala
Implement changes requested on **SPOT-196**. Decouples SpotLDAWrapper functionality in preparation for next steps of spot-ml including plans for near real-time. 
Refactored SpotLDAWrapper into new objects/classes in order to support further uses of spot-ml and/or new applications.
The current implementation supports only training a model and getting topicsMatrix + topicDistributions in the format Spot ML requires it for scoring. Two new features are added:
1. Ability to save a model and load an existing model
2. Ability to predict new documents using OnlineLDAOptimizer
New objects: 
- _SpotLDAHelper_: Receives and RDD with document word count information and the floating point precision users want to use for training and getting results. The object will offer a method to return the corpus …
> Spot-196 [ML] Spot LDA Wrapper refactoring

- spot-oa/requirements.txt
There seem to be backwards incompatibilities with graphql-core 2+ and we need to ensure that the version installed is 1.1 for everything to work properly.
> Spot 243 Specify graphql-core version 1.1 support

- spot-oa/api/graphql/webapp.py
- spot-oa/requirements.txt
- spot-setup/spot.conf
Enabling CORS with the ability to configure origins allows additional applications to use and support the Spot GraphQL API.
Tasks
- Add "flask-cors" to requirements.txt
- Use CORS with GraphQL app blueprint
- Add a configuration in spot.conf for origin specification
> Spot 244 enable cors on graphql api

- spot-oa/oa/dns/dns_oa.py
Stop the start_oa.py script from crashing, while performing reputation check for the dns_results.csv domains. 
https://issues.apache.org/jira/browse/SPOT-238
> SPOT-238 Fix dns_oa.py to stop crashing FBThreatExchange

- spot-ingest/streamsets/netflow/NetFlowODMandLegacy.json
This adds a starter config for using StreamSets to ingest NetFlow data into the ODM,
as well as legacy Parquet tables. It's primarily designed for NetFlow v9, but should
support NetFlow v5, as well.
> SPOT-245. StreamSets pipeline for NetFlow data into ODM

- spot-ingest/streamsets/windows/ODMWindowsEventLogs.json
- spot-ingest/streamsets/windows/WindowsHTTPEdge.json
This updates the ODMWindowsEventLogs pipeline to consume off of an HTTP Server origin,
which will receive data from an SDC Edge pipeline sending System, Security, or Application
logs over an HTTP connection. This is intended as a configurable starting point, as there
will likely be additional customization required for any real-world environment. SDC
does not easily run on Windows, so SDC Edge will allow offload of Windows logs to an SDC
pipeline that delivers data into the ODM schema.
Windows to HTTP:
HTTP Server to ODM:
> SPOT-249. Update Windows Event Log ingest to support SDC Edge

- spot-oa/arcadia/README.md
- spot-setup/odm/README.md
- Old ONI wiki and issue links were changed and committed to use the new Spot links, but for some reason the changes didn't take after the PR (https://github.com/apache/incubator-spot/pull/119)
- Also made a small update in the arcadia/README.md instructions for loading sample data.  Sample data loading use the "odm_sample_setup.sh" script now requires a format argument to ensure sample data is loaded into the ODM tables properly (i.e. `./odm_sample_setup.sh pqt` or `./odm_sample_setup.sh avro`).
> Spot 235 fix deprecated links in odm setup

- spot-oa/api/resources/flow.py
The code assumes that there are always inbound only and outbound only connections. This causes saving a scored threat that has either no inbound, or outbound only connections. Fix is simply moving the column header row to outside the check, so the array element is always initialized before being accessed.
Tested the following case
a) Inbound and Twoway only
b) Outbound only
c) Outbound and twoway only
> Incorrect assumption inbound/outbound crashes

- spot-setup/odm/event.avsc
The Avro and Parquet table schemas designate the additional_attrs field as a map<string, string>, but in the Avro schema definition (in event.avsc), the field is listed as just an optional string. This field should be updated to be an optional map<string>
> SPOT-261. ODM event schema additional_attrs field should be map<string>

- spot-setup/odm/odm_setup.sh
- spot-setup/spot.conf
- This PR is a combination of cherry picks from #134 
- Update odm_setup.sh to include arguments for sudo-less execution (--no-sudo), custom paths for spot.conf (-c), and updated the format argument to specified using the "-f" flag.
- odm_setup.sh now more gracefully handles errors and hdfs directory creation.
- Improved logging
- Updated spot.conf to include Kerberos and SSL configurations
> Spot 263 add kerberos support for odm setup

- spot-ingest/start_ingest_standalone.sh
Hi there,
PR #128 introduced a portable path to bash. This PR extends #128 and fixes the hardcoded path to bash when being called by `screen`.
Cheers,
tpltnt
> flexible path to bash when calling screen

- spot-ingest/pipelines/proxy/worker.py
Documentation at `incubator-spot/spot-ingest/README.md` refers to Kafka jar as spark-streaming-kafka-0-8-assembly_2.11. This file didn't, so I have made the tweak to avoid future confusion.
Cheers,
Rob
> Edited to match documentation

- LICENSE
- NOTICE
Resolves [SPOT-296](https://issues.apache.org/jira/browse/SPOT-296).  There were some dependency copyrights in the LICENSE file that needed updating to 2020 as well as the NOTICE file.
> Spot 296 update copyright year in master

- spot-ingest/pipelines/flow/load_flow_avro_parquet.hql
- spot-ingest/pipelines/flow/worker.py
In two instances, Avro files are created with internal schema where one of the fields "ibyt" was mis-spelled "ibytt".  This corrects that.
> Spot 304 fix inconsistencies between hive and avro

- index.html
In SPOT-299, we were trying to add the required ASF site to the home page.  However, after we reviewed the Whimsy logs, it is not enough for links to be available on the home page, the html must actually regex the links.  After reviewing other ASF projects, we found out that Livy had a drop-down menu like ours, that was easily adapted to our needs.  Thus, this change fulfills the intention of SPOT-299 and complies with ASF regulations.
> SPOT-299 Asf site whimsy fixes
